version: "2"

services:

  web:
    build: .
    volumes:
      - ./src:/data/www/kaylv
      - ./config/supervisor.conf:/etc/supervisor.conf
      - ./config/supervisor.fpm.conf:/etc/supervisor.d/fpm.conf
      - ./config/supervisor.nginx.conf:/etc/supervisor.d/nginx.conf
      - ./config/nginx.default.conf:/usr/local/nginx/nginx.conf
    ports:
      - "8700:80"
